apiVersion: redhatcop.redhat.io/v1alpha1
kind: GlobalDNSRecord
metadata:
  name: route53-geoproximity-global-record-with-healthcheck
spec:
  name: geoproximity-hc.${global_base_domain}
  endpoints:
  - clusterName: cluster1
    clusterCredentialRef:
      name: secret1
      namespace: cluster1
    loadBalancerServiceRef:
      name: cluster-default
      namespace: openshift-ingress
  - clusterName: cluster2
    clusterCredentialRef:
      name: secret2
      namespace: cluster2
    loadBalancerServiceRef:
      name: cluster-default
      namespace: openshift-ingress
  - clusterName: cluster3
    clusterCredentialRef:
      name: secret3
      namespace: cluster3
    loadBalancerServiceRef:
      name: cluster-default
      namespace: openshift-ingress
  ttl: 60
  loadBalancingPolicy: Geoproximity
  globalZoneRef:
    name: route53-global-dns-zone
  healthCheck:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
    failureThreshold: 3
    httpGet: 
      host: geoproximity-hc.${global_base_domain}
      port: 80
      scheme: HTTP
      path: /healthz  