kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-load-balancer-operator
  namespace: {{ .Release.Namespace }}  
subjects: 
- kind: ServiceAccount
  name: global-load-balancer-operator
roleRef:
  kind: Role
  name: global-load-balancer-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-load-balancer-operator
subjects:
- kind: ServiceAccount
  name: global-load-balancer-operator
  namespace: {{ .Release.Namespace }} 
roleRef:
  kind: ClusterRole
  name: global-load-balancer-operator
  apiGroup: rbac.authorization.k8s.io 