apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: global-load-balancer-operator
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnszones
  - globaldnszones/finalizers
  - globaldnszones/status
  - globaldnsrecords
  - globaldnsrecords/finalizers
  - globaldnsrecords/status
  - globalroutediscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
