apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ template "acm-aws-cluster.fullname" . }}
spec:
  clusterName: {{ template "acm-aws-cluster.fullname" . }}
  clusterNamespace: {{ .Release.Namespace }}
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.0.0